DROP DATABASE IF EXISTS compta;

CREATE DATABASE IF NOT EXISTS compta;

USE compta;

CREATE TABLE IF NOT EXISTS article(
    ID int(11) PRIMARY KEY,
    REF varchar(13),
    DESIGNATION varchar(255),
    PRIX decimal(7,2),
    ID_FOU int(11)
);

CREATE TABLE IF NOT EXISTS fournisseur(
    ID int(11) PRIMARY KEY,
    NOM varchar(25)
);

CREATE TABLE IF NOT EXISTS bon(
    ID int(11) PRIMARY KEY,
    NUMERO int(11),
    DATE_CMDE datetime,
    DELAI int(11),
    ID_FOU int(11)
);

CREATE TABLE IF NOT EXISTS compo(
    ID int(11) AUTO_INCREMENT PRIMARY KEY,
    ID_ART int(11),
    ID_BON int(11),
    QTE int(11)
);

ALTER TABLE article ADD CONSTRAINT FOREIGN KEY (ID_FOU) REFERENCES fournisseur(ID);
ALTER TABLE bon ADD CONSTRAINT FOREIGN KEY (ID_FOU) REFERENCES fournisseur(ID);
ALTER TABLE compo ADD CONSTRAINT FOREIGN KEY (ID_ART) REFERENCES article(ID);
ALTER TABLE compo ADD CONSTRAINT FOREIGN KEY (ID_BON) REFERENCES bon(ID);





